const initialStudents = [
  {
    studentId: "PM201",
    fullName: "ThS.Võ Hải Long",
    dob: "40",
    classRoom: "Phòng thực hành Lập trình web",
    // gpa: "3.5",
    email: "long.vh@tlu.edu.vn",
    // password: "Password123!",
  },
  {
  //   studentId: "SV234567",
  //   fullName: "Trần Thị B",
  //   dob: "1999-05-20",
  //   classRoom: "B",
  //   // gpa: "3.1",
  //   email: "btt@student.edu.vn",
  //   // password: "Password123!",
  // },
  // {
  //   studentId: "SV345678",
  //   fullName: "Lê Văn C",
  //   dob: "2001-03-10",
  //   classRoom: "C",
  //   // gpa: "3.1",
  //   email: "clv@student.edu.vn",
  //   // password: "Password123!",
  // },
  // {
  //   studentId: "SV456789",
  //   fullName: "Phạm Thị D",
  //   dob: "2000-07-25",
  //   classRoom: "D",
  //   // gpa: "2.4",
  //   email: "dpt@student.edu.vn",
  //   // password: "Password123!",
  // },
  // {
  //   studentId: "SV567890",
  //   fullName: "Hoàng Văn E",
  //   dob: "1998-12-05",
  //   classRoom: "A",
  //   // gpa: "4.0",
  //   email: "ehv@st /udent.edu.vn",
  //   // password: "Password123!",
  // },
];
